name: Test and Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the two latest versions
        run: |
          CURRENT_VERSION=$(git tag -l "v*" --sort=-version:refname | head -n 1)
          LAST_VERSION=$(git tag -l "v*" --sort=-version:refname | head -n 2 | awk 'NR == 2 { print $1 }')
          echo "current_version=$(echo $CURRENT_VERSION)" >> $GITHUB_ENV
          echo "last_version=$(echo $LAST_VERSION)" >> $GITHUB_ENV

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          corepack: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: |
          pnpm nx run-many --target=lint --all
          pnpm nx run-many --target=build --all --prod
