name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the two latest versions
        run: |
          CURRENT_VERSION=$(git tag -l "v*" --sort=-version:refname | head -n 1)
          LAST_VERSION=$(git tag -l "v*" --sort=-version:refname | head -n 2 | awk 'NR == 2 { print $1 }')
          echo "current_version=$(echo $CURRENT_VERSION)" >> $GITHUB_ENV
          echo "last_version=$(echo $LAST_VERSION)" >> $GITHUB_ENV

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          corepack: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build libraries
        run: |
          pnpm nx affected:build --prod --base=$last_version --head=$current_version
      - name: Publish components (Npm packages)
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          cat ~/.npmrc
          for LIBRARY in $(pnpm nx affected:libs --base=$last_version --head=$current_version --plain)
          do
            cd ./packages/$(echo $LIBRARY| cut -d'/' -f 2)
            npm publish --no-git-tag-version --no-push --yes
            cd ..
            cd ..
          done
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
